var dir_36df885461d6bd14211edf06510d126c =
[
    [ "article.class.php", "article_8class_8php.html", "article_8class_8php" ],
    [ "article.dao.php", "article_8dao_8php.html", "article_8dao_8php" ],
    [ "game.class.php", "game_8class_8php.html", "game_8class_8php" ],
    [ "game.dao.php", "game_8dao_8php.html", "game_8dao_8php" ],
    [ "gameRecord.class.php", "gameRecord_8class_8php.html", "gameRecord_8class_8php" ],
    [ "gameRecord.dao.php", "gameRecord_8dao_8php.html", "gameRecord_8dao_8php" ],
    [ "invoice.class.php", "invoice_8class_8php.html", "invoice_8class_8php" ],
    [ "invoice.dao.php", "invoice_8dao_8php.html", "invoice_8dao_8php" ],
    [ "moderator.class.php", "moderator_8class_8php.html", "moderator_8class_8php" ],
    [ "moderator.dao.php", "moderator_8dao_8php.html", "moderator_8dao_8php" ],
    [ "passwordResetToken.class.php", "passwordResetToken_8class_8php.html", "passwordResetToken_8class_8php" ],
    [ "passwordResetToken.dao.php", "passwordResetToken_8dao_8php.html", "passwordResetToken_8dao_8php" ],
    [ "penalty.class.php", "penalty_8class_8php.html", "penalty_8class_8php" ],
    [ "penalty.dao.php", "penalty_8dao_8php.html", "penalty_8dao_8php" ],
    [ "player.class.php", "player_8class_8php.html", "player_8class_8php" ],
    [ "player.dao.php", "player_8dao_8php.html", "player_8dao_8php" ],
    [ "rememberToken.class.php", "rememberToken_8class_8php.html", "rememberToken_8class_8php" ],
    [ "rememberToken.dao.php", "rememberToken_8dao_8php.html", "rememberToken_8dao_8php" ],
    [ "report.class.php", "report_8class_8php.html", "report_8class_8php" ],
    [ "report.dao.php", "report_8dao_8php.html", "report_8dao_8php" ],
    [ "statistics.class.php", "statistics_8class_8php.html", "statistics_8class_8php" ],
    [ "suggestion.class.php", "suggestion_8class_8php.html", "suggestion_8class_8php" ],
    [ "suggestion.dao.php", "suggestion_8dao_8php.html", "suggestion_8dao_8php" ],
    [ "user.class.php", "user_8class_8php.html", "user_8class_8php" ],
    [ "user.dao.php", "user_8dao_8php.html", "user_8dao_8php" ]
];