var hierarchy =
[
    [ "Article", "classComusParty_1_1Models_1_1Article.html", null ],
    [ "ArticleDAO", "classComusParty_1_1Models_1_1ArticleDAO.html", null ],
    [ "Controller", "classComusParty_1_1Controllers_1_1Controller.html", [
      [ "ControllerAuth", "classComusParty_1_1Controllers_1_1ControllerAuth.html", null ],
      [ "ControllerBasket", "classComusParty_1_1Controllers_1_1ControllerBasket.html", null ],
      [ "ControllerDashboard", "classComusParty_1_1Controllers_1_1ControllerDashboard.html", null ],
      [ "ControllerGame", "classComusParty_1_1Controllers_1_1ControllerGame.html", null ],
      [ "ControllerPolicy", "classComusParty_1_1Controllers_1_1ControllerPolicy.html", null ],
      [ "ControllerProfile", "classComusParty_1_1Controllers_1_1ControllerProfile.html", null ],
      [ "ControllerRanking", "classComusParty_1_1Controllers_1_1ControllerRanking.html", null ],
      [ "ControllerShop", "classComusParty_1_1Controllers_1_1ControllerShop.html", null ],
      [ "ControllerSuggestion", "classComusParty_1_1Controllers_1_1ControllerSuggestion.html", null ]
    ] ],
    [ "ControllerFactory", "classComusParty_1_1Controllers_1_1ControllerFactory.html", null ],
    [ "Cookie", "classComusParty_1_1App_1_1Cookie.html", null ],
    [ "Db", "classComusParty_1_1App_1_1Db.html", null ],
    [ "EloCalculator", "classComusParty_1_1App_1_1EloCalculator.html", null ],
    [ "Exception", null, [
      [ "AuthenticationException", "classComusParty_1_1App_1_1Exceptions_1_1AuthenticationException.html", null ],
      [ "GameSettingsException", "classComusParty_1_1App_1_1Exceptions_1_1GameSettingsException.html", null ],
      [ "GameUnavailableException", "classComusParty_1_1App_1_1Exceptions_1_1GameUnavailableException.html", null ],
      [ "MalformedRequestException", "classComusParty_1_1App_1_1Exceptions_1_1MalformedRequestException.html", null ],
      [ "NotFoundException", "classComusParty_1_1App_1_1Exceptions_1_1NotFoundException.html", [
        [ "ControllerNotFoundException", "classComusParty_1_1App_1_1Exceptions_1_1ControllerNotFoundException.html", null ],
        [ "MethodNotFoundException", "classComusParty_1_1App_1_1Exceptions_1_1MethodNotFoundException.html", null ],
        [ "RouteNotFoundException", "classComusParty_1_1App_1_1Exceptions_1_1RouteNotFoundException.html", null ]
      ] ],
      [ "PaymentException", "classComusParty_1_1App_1_1Exceptions_1_1PaymentException.html", null ],
      [ "UnauthorizedAccessException", "classComusParty_1_1App_1_1Exceptions_1_1UnauthorizedAccessException.html", null ]
    ] ],
    [ "Game", "classComusParty_1_1Models_1_1Game.html", null ],
    [ "GameDAO", "classComusParty_1_1Models_1_1GameDAO.html", null ],
    [ "GameRecord", "classComusParty_1_1Models_1_1GameRecord.html", null ],
    [ "GameRecordDAO", "classComusParty_1_1Models_1_1GameRecordDAO.html", null ],
    [ "Invoice", "classComusParty_1_1Models_1_1Invoice.html", null ],
    [ "InvoiceDAO", "classComusParty_1_1Models_1_1InvoiceDAO.html", null ],
    [ "Mailer", "classComusParty_1_1App_1_1Mailer.html", null ],
    [ "MessageComponentInterface", null, [
      [ "Chat", "classComusParty_1_1App_1_1Sockets_1_1Chat.html", null ],
      [ "Dashboard", "classComusParty_1_1App_1_1Sockets_1_1Dashboard.html", null ],
      [ "Game", "classComusParty_1_1App_1_1Sockets_1_1Game.html", null ]
    ] ],
    [ "MessageHandler", "classComusParty_1_1App_1_1MessageHandler.html", null ],
    [ "Moderator", "classComusParty_1_1Models_1_1Moderator.html", null ],
    [ "ModeratorDAO", "classComusParty_1_1Models_1_1ModeratorDAO.html", null ],
    [ "PasswordResetToken", "classComusParty_1_1Models_1_1PasswordResetToken.html", null ],
    [ "PasswordResetTokenDAO", "classComusParty_1_1Models_1_1PasswordResetTokenDAO.html", null ],
    [ "Penalty", "classComusParty_1_1Models_1_1Penalty.html", null ],
    [ "PenaltyDAO", "classComusParty_1_1Models_1_1PenaltyDAO.html", null ],
    [ "Player", "classComusParty_1_1Models_1_1Player.html", null ],
    [ "PlayerDAO", "classComusParty_1_1Models_1_1PlayerDAO.html", null ],
    [ "RememberToken", "classComusParty_1_1Models_1_1RememberToken.html", null ],
    [ "RememberTokenDAO", "classComusParty_1_1Models_1_1RememberTokenDAO.html", null ],
    [ "Report", "classComusParty_1_1Models_1_1Report.html", null ],
    [ "ReportDAO", "classComusParty_1_1Models_1_1ReportDAO.html", null ],
    [ "Router", "classComusParty_1_1App_1_1Router.html", null ],
    [ "Statistics", "classComusParty_1_1Models_1_1Statistics.html", null ],
    [ "Suggestion", "classComusParty_1_1Models_1_1Suggestion.html", null ],
    [ "SuggestionDAO", "classComusParty_1_1Models_1_1SuggestionDAO.html", null ],
    [ "User", "classComusParty_1_1Models_1_1User.html", null ],
    [ "UserDAO", "classComusParty_1_1Models_1_1UserDAO.html", null ],
    [ "Validator", "classComusParty_1_1App_1_1Validator.html", null ]
];